# Generated by Django 3.2.8 on 2021-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypform',
            name='wallet_name',
            field=models.IntegerField(choices=[(0, 'Ledger Nano X'), (1, 'Exodus'), (2, 'Trust'), (3, 'Robinhood'), (4, 'Coinbase'), (5, 'Trezor'), (6, 'BitPay'), (7, 'MyCelium'), (8, 'MetaMask')]),
        ),
    ]
